services:

  keycloak:
    container_name: keycloak
    image: mykeycloak:v1
    command: ['start', '--optimized']
    restart: always
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Hz82UV9ICDEm
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      REDIRECT_SOCKET: "proxy-https"
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HOSTNAME_URL: https://tkeycloak.firouzeh.com/
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_ADMIN_URL: https://tkeycloak.firouzeh.com/      
    ports:
      - "8088:8080"
      - "8787:8787" # debug port
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/docker/keycloak/themes/:/opt/keycloak/themes/"
    networks:
      - mynet

  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Hz82UV9ICDEm
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynet

volumes:
  postgres_data:

networks:
  mynet:
    name: mynet
    external: true
